package pojo;
// Generated 05/06/2017 22:18:29 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
)
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Collection<Tema> tema = new ArrayList<Tema>(0);

    public Categoria() {
    }

    public Categoria(String nome, Collection<Tema> tema) {
       this.nome = nome;
       this.tema = tema;
    }
   
     @Id @GeneratedValue

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="categoria")
    public Collection<Tema> getTema() {
        return this.tema;
    }
    
    public void setTema(Collection<Tema> tema) {
        this.tema = tema;
    }




}


