package pojo;
// Generated 05/06/2017 22:18:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name="tema"
)
public class Tema  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Date datacompra;
     private String descricao;
     private char genero;
     private String nome;
     private double preco;
     private String status;

    public Tema() {
    }

	
    public Tema(char genero, double preco) {
        this.genero = genero;
        this.preco = preco;
    }
    public Tema(Categoria categoria, Date datacompra, String descricao, char genero, String nome, double preco, String status) {
       this.categoria = categoria;
       this.datacompra = datacompra;
       this.descricao = descricao;
       this.genero = genero;
       this.nome = nome;
       this.preco = preco;
       this.status = status;
    }
   
     @Id @GeneratedValue

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idcategoria")
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datacompra")
    public Date getDatacompra() {
        return this.datacompra;
    }
    
    public void setDatacompra(Date datacompra) {
        this.datacompra = datacompra;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="genero", nullable=false)
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }

    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="preco", nullable=false)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


